import type { Card, CardDefinitionId, CreatureCard, SpellCard } from './types'

export const CARD_DEFINITION_IDS = {
  SPARK_SWORDSMAN: '76bd5e86-4630-4f43-97d9-c63cfb3435d4',
  TIDEWAY_SCOUT: 'd586b116-629c-46ff-bb00-4d21c68b6c48',
  OAKBARK_SENTINEL: '42472077-8185-422c-b71c-7a4550cda508',
  BURNING_VANGUARD: 'f6a28bee-9dfe-4686-ad11-ace2053d6bbd',
  SPRAY_HERALD: '24112ba6-4b8e-4b78-971d-4af441ed6fcd',
  ROOTED_ANCIENT: 'bdfacb0b-341d-4c0a-9ec8-fc9b8b627eb7',
  BEACON_HEAVY_CAVALRY: '220d6546-8f8a-48bf-b50c-2351c61b69ef',
  AZURE_WAVE_VOYAGER: '4b9a780b-c61a-437a-849e-72cd1b83b342',
  GREAT_TREE_GUARDIAN: 'dc2f752b-bbf5-4f2d-8af6-c3277ef9e886',
  EXHAUSTED_VOLCANO_DRAGON: 'aa7406ae-8466-4422-a427-5bb5bf62360c',
  EPHEMERAL_DEEP_WHALE: 'f58f7a5c-9062-4bee-b480-3a8faab335ab',
  DREAMWALKING_FOREST_GIANT: '87100751-7dc9-4d6e-8eff-b997b549efb7',
  SOLITARY_PEAK_SWORDSMAN: '2ab6a395-f24a-46dd-8dc3-3de3c9662dcb',
  FORMATION_CLEARING_MERCENARY: '226f2c8a-b3d3-4686-bb51-a8333a869684',
  CRIMSON_BLADE_INFILTRATOR: '1ce68905-d722-4bc0-8fc9-54a23e49bb11',
  SURGING_DUELIST: '404a833c-f5c7-46a5-8002-cd9ebf77d288',
  MIST_RETURNING_MESSENGER: 'ec950f12-0b17-41a2-8313-dc7e371e9498',
  TIDEFRONT_FORTIFIER: '8a1c867a-c5bf-4a85-8235-c803bf9c6636',
  VINE_SNARE_HUNTER: 'd88ebb3e-dea6-44ba-8137-65c7d43c2e21',
  GEODE_MINER: '558df3f0-8431-490f-bcb8-1ffbfd9f809d',
  ROOT_FORT_REARGUARD: '9d13120c-af42-4177-a04e-3347e9db6112',
  LONE_ARMY_GENERAL: '0f977549-313e-4012-8912-e562d1eda3c7',
  ASH_DISMANTLER: '115cdda8-9b82-4335-8300-4fdc771b150a',
  DEEP_TIDE_INTERCEPTOR: 'b9c266d6-7f89-4a3b-b1dc-7032c316241f',
  WAVE_RETURN_MAGE: 'a2930f95-2867-4e28-bb74-133d4e66c7b1',
  FOREST_CAGE_BEASTMASTER: '45fec150-1a32-4a7f-b7b4-be238484324e',
  LEYLINE_MINING_GIANT: 'd0d92b6e-55f7-4f1b-8023-bc3b067400ae',
  RETURN_FIRE: '747911c4-29db-4fbc-a056-fb97b29c275f',
  LIFE_DROPLET: 'f76eb155-8b41-401d-aa94-83ebcdcaec73',
  ABUNDANCE: 'f1f9c2ec-1db5-46e3-b6f0-5ca0ef958bdb',
  FIREBALL_ASSAULT: 'aab9db3e-2214-4bf8-81e2-154b489c2c51',
  TRANSFER: 'd802b528-da1b-4474-9acf-ddd9c3978f61',
  LIFE_CYCLE: '71101851-b5aa-4f63-9071-60e470a49009',
  MEPHISTOPHELES: '094c4047-a55a-4001-ae91-b562f15b66f7',
  MAGICIAN: 'b67d6803-0077-4a65-ad0b-68dcc7fcc546',
  THIEF: 'ca42b887-4e49-497e-8472-543c35559ae2',
  SELF_DESTRUCT_ORDER: '4082a8a2-f853-444d-90b7-fde4ff13d96b',
  BRIBERY: 'eb863aef-a524-4d6d-84ed-6d4f7e3b33a1',
  CANNON: '80c448c1-5eef-42f6-9797-4f083e1fb6b6',
  CATACLYSM: '2ef4e015-72dc-4538-892e-a31bab369607',
  GIANT_FROG: 'bcf14485-d233-4a0e-bb1e-bc93338e4aa9',
  WORLD_SERPENT: '108c96ea-99a7-4fff-aca0-8105915327db',
} as const satisfies Record<string, CardDefinitionId>

export const EXPANSION_CARD_DEFINITION_IDS = [
  CARD_DEFINITION_IDS.MEPHISTOPHELES,
  CARD_DEFINITION_IDS.MAGICIAN,
  CARD_DEFINITION_IDS.THIEF,
  CARD_DEFINITION_IDS.SELF_DESTRUCT_ORDER,
  CARD_DEFINITION_IDS.BRIBERY,
  CARD_DEFINITION_IDS.CANNON,
  CARD_DEFINITION_IDS.CATACLYSM,
  CARD_DEFINITION_IDS.GIANT_FROG,
  CARD_DEFINITION_IDS.WORLD_SERPENT,
] as const satisfies readonly CardDefinitionId[]

export const CREATURE_CARDS = [
  {
    definitionId: CARD_DEFINITION_IDS.WORLD_SERPENT,
    name: '世界蛇',
    foil: true,
    kind: 'creature',
    color: 'green',
    cost: 6,
    attack: 8,
    defense: 8,
    march: 3,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.GIANT_FROG,
    name: '大蛙',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 3,
    defense: 3,
    march: 1,
    abilities: [{ type: 'gluttony' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.SPARK_SWORDSMAN,
    name: '山賊',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 3,
    defense: 2,
    march: 1,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.TIDEWAY_SCOUT,
    name: '行商人',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 3,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.OAKBARK_SENTINEL,
    name: '番兵',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 3,
    march: 1,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.BURNING_VANGUARD,
    name: '飢えた狼',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 4,
    defense: 1,
    march: 0,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.SPRAY_HERALD,
    name: '渡り鳥',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 2,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.ROOTED_ANCIENT,
    name: '重装兵',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 4,
    march: 0,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.BEACON_HEAVY_CAVALRY,
    name: '投石機',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 6,
    defense: 2,
    march: 1,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.AZURE_WAVE_VOYAGER,
    name: '海賊船',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 5,
    defense: 5,
    march: 3,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.GREAT_TREE_GUARDIAN,
    name: '戦象',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 5,
    defense: 6,
    march: 1,
    abilities: [],
  },
  {
    definitionId: CARD_DEFINITION_IDS.EXHAUSTED_VOLCANO_DRAGON,
    foil: true,
    name: 'ドラゴン',
    kind: 'creature',
    color: 'red',
    cost: 5,
    attack: 7,
    defense: 4,
    march: 2,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.EPHEMERAL_DEEP_WHALE,
    name: '白鯨',
    kind: 'creature',
    color: 'blue',
    cost: 5,
    attack: 6,
    defense: 6,
    march: 4,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.DREAMWALKING_FOREST_GIANT,
    name: 'ゴーレム',
    kind: 'creature',
    color: 'green',
    cost: 5,
    attack: 6,
    defense: 7,
    march: 2,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.SOLITARY_PEAK_SWORDSMAN,
    name: 'ゴリラ',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 1,
    abilities: [{ type: 'loneWarrior', attack: 2, defense: 0 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.FORMATION_CLEARING_MERCENARY,
    name: '荒くれ者',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: [{ type: 'withdraw' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.CRIMSON_BLADE_INFILTRATOR,
    name: '暗殺者',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 1,
    abilities: [{ type: 'assassin', attack: 2 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.SURGING_DUELIST,
    name: 'ウニ',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: [{ type: 'counter' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.MIST_RETURNING_MESSENGER,
    name: '傭兵',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: [{ type: 'rally' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.TIDEFRONT_FORTIFIER,
    name: '偵察者',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 2,
    abilities: [{ type: 'beachhead', costReduction: 1 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.VINE_SNARE_HUNTER,
    name: '狩人',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 3,
    march: 0,
    abilities: [{ type: 'capture', marchTax: 1 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.GEODE_MINER,
    name: '鉱夫',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: [{ type: 'mining', mana: 1 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.ROOT_FORT_REARGUARD,
    name: '墓守',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: [{ type: 'rearguard', attack: 0, defense: 2 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.LONE_ARMY_GENERAL,
    name: 'バーサーカー',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 4,
    defense: 2,
    march: 1,
    abilities: [{ type: 'loneWarrior', attack: 3, defense: 1 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.ASH_DISMANTLER,
    name: '巨大なワーム',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 6,
    defense: 1,
    march: 1,
    abilities: [{ type: 'withdraw' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.DEEP_TIDE_INTERCEPTOR,
    foil: true,
    name: 'クラーケン',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 4,
    defense: 4,
    march: 2,
    abilities: [{ type: 'counter' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.WAVE_RETURN_MAGE,
    name: '援軍',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 4,
    defense: 4,
    march: 2,
    abilities: [{ type: 'rally' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.FOREST_CAGE_BEASTMASTER,
    foil: true,
    name: '大蜘蛛',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 4,
    defense: 5,
    march: 1,
    abilities: [{ type: 'capture', marchTax: 2 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.LEYLINE_MINING_GIANT,
    name: '職人ギルド',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 4,
    defense: 4,
    march: 1,
    abilities: [{ type: 'mining', mana: 1 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.MEPHISTOPHELES,
    foil: true,
    name: 'メフィストフェレス',
    kind: 'creature',
    color: 'red',
    cost: 1,
    attack: 6,
    defense: 4,
    march: 1,
    abilities: [{ type: 'installment', mana: 2 }, { type: 'vanish' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.MAGICIAN,
    name: '奇術師',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 1,
    defense: 1,
    march: 2,
    abilities: [{ type: 'trickster', amount: 4 }, { type: 'rally' }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.THIEF,
    name: '盗賊',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 1,
    abilities: [{ type: 'plunder', mana: 2 }],
  },
  {
    definitionId: CARD_DEFINITION_IDS.CANNON,
    name: '攻城砲',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 0,
    defense: 2,
    march: 1,
    abilities: [{ type: 'bombardment', damage: 6 }],
  },
] satisfies CreatureCard[]

export const SPELL_CARDS = [
  {
    definitionId: CARD_DEFINITION_IDS.RETURN_FIRE,
    name: 'バックドラフト',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'returnFire', exileColor: 'red' },
    text: '自分の捨て札にあるすべての赤クリーチャーを除外する。自プレイヤーに隣接するグループへ、除外した枚数に等しいダメージを与える。このダメージは通常攻撃と同じように伝播・減衰する。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.LIFE_DROPLET,
    name: '生命の雫',
    kind: 'spell',
    cost: 0,
    duration: 'untilNextTurnStart',
    effect: { type: 'lifeDroplet', exileColor: 'blue' },
    text: '自分の捨て札にあるすべての青クリーチャーを除外する。除外した枚数に等しいHPを回復する。次の自分のターン開始まで、自プレイヤーのシールドを除外した枚数だけ増やす。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.ABUNDANCE,
    name: '収穫祭',
    kind: 'spell',
    cost: 0,
    duration: 'untilTurnEnd',
    effect: { type: 'abundance', exileColor: 'green' },
    text: '自分の捨て札にあるすべての緑クリーチャーを除外し、その枚数に等しいマナを得る。ターン終了時にすべてのマナを失う。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.FIREBALL_ASSAULT,
    name: '火の玉特攻',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'fireballAssault' },
    text: '自分のグループを1つ選択する。そのグループの赤クリーチャーをすべて破壊する。敵プレイヤーのHPを、破壊されたクリーチャーのコストの合計だけ減少させる。この効果はシールドの影響を受けない。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.TRANSFER,
    name: 'テレポート',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'transfer' },
    text: '自分の青クリーチャー1体を選択する。そのクリーチャーを最もHPの少ないプレイヤーの隣に移動する。双方のHPが同じ場合は移動しない。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.LIFE_CYCLE,
    foil: true,
    name: '生命の循環',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'lifeCycle' },
    text: '自分のすべての緑クリーチャーを破壊する。この効果による破壊では半分ではなく全額のマナが返還される。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.SELF_DESTRUCT_ORDER,
    name: '自爆命令',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'selfDestructOrder' },
    text: '自分のクリーチャー1体を選択する。そのクリーチャーが所属するグループと、その両隣のグループにいるすべてのクリーチャーへ、選んだクリーチャーのコストに等しいダメージを与える。プレイヤーはダメージを受けない。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.BRIBERY,
    name: '買収',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'bribery' },
    text: '相手クリーチャー1体を選択する。そのクリーチャーのコスト＋1を支払う。支払えた場合、そのクリーチャーのコントロールを得る。',
  },
  {
    definitionId: CARD_DEFINITION_IDS.CATACLYSM,
    name: '天変地異',
    kind: 'spell',
    cost: 0,
    duration: 'immediate',
    effect: { type: 'cataclysm' },
    text: 'すべてのクリーチャーの並びを逆順に並び替える。',
  },
] satisfies SpellCard[]

export const CARD_LIST = [
  ...CREATURE_CARDS,
  ...SPELL_CARDS,
] satisfies Card[]

export const CARD_BY_DEFINITION_ID = Object.fromEntries(
  CARD_LIST.map((card) => [card.definitionId, card]),
) as Partial<Record<CardDefinitionId, Card>>
